### ISSUE TITLE
Allow variable substitution and expression evaluation as part of a line statement

### ISSUE THREAD

**Issue by lordmortis** [thesecretlab/YarnSpinner#123]
We should have substitution in line statements.
variable substitution:
```
Did you mean the {$leverColor} coloured lever?
```

expression evaluation:
```
Did you mean the {leverColor()} coloured lever?
```

**Comment by BlindElephants** [comment]
I second this. Been trying to figure out how to do my own implementation of this. Any thoughts or ideas about getting this working in the short term?

**Comment by lordmortis** [comment]
We’ve done some ground work towards this in the Jacquard runtime and associated tooling but haven’t started work on a Unity runtime yet

**Comment by TheMartianLife** [comment]
Though the title may make it sound otherwise, this issue is actually covered in #39 as a required step---along with proposed implementation details. Interpolation is on the roadmap, but it's a bigger (and more breaking change) than you may imagine because of the features that commonly go along with it and users will expect.

But thanks so much for getting in touch! Follow along at #39 :)
