### ISSUE TITLE
YarnSpinner float parsing problem on custom commands

### ISSUE THREAD

**Issue by tomdominer** [thesecretlab/YarnSpinner#148]
YarnSpinner seems to be having trouble parsing floats with more than two decimal places when trying to call my custom YarnSpinner function "set_text_speed".

This command parses:                **<<set_text_speed(0.5)>>**
but this command does not:      **<<set_text_speed(0.05)>>**

I get this error: _ParseException: In file <input>: Error parsing node Choice.Punish.White.Noise: Line 3:20: Error parsing expression (stack did not reduce correctly)_

**Comment by TheMartianLife** [comment]
Hi, 

Thanks for letting us know. We've looked into a few related bugs on float parsing but can't seem to figure out why this would occur for you. If you could please respond with your function declaration for **set_text_speed()** and some context around where it is called? 

Then we may be able to both figure out your issue and also whether it would be something affecting everyone.

Thanks!

**Comment by TheMartianLife** [comment]
As referenced in #169 we believe this may be due to incorrect tokenising of floating point numbers with 2+ decimal places. The stream would consume 0.0 as the parameter, leaving a 5 hanging when it expects either a comma or closed parenthesis. 

Closing this issue, but let us know if you encounter any further weird behaviour :)
