### ISSUE TITLE
Not sure what's up here

### ISSUE THREAD

**Issue by InfiniteAmmoInc** [thesecretlab/YarnSpinner#21]
https://dl.dropboxusercontent.com/u/1063919/Screen%20Shot%202016-02-23%20at%2012.22.37%20PM.png

When running this text, I get a call to my run options function with 0 options. (every time running it, before getting to the if chunk with the actual options in it)

I also see "Cannot continue running dialogue. Still waiting on option selection." But things continue running fine.

**Comment by desplesda** [comment]
Ah, it might be doing something odd with the “[“ and “]” in those lines.. Can you upload that text as an attachment to this issue? I can then add it to the test case collection.

**Comment by desplesda** [comment]
Ah! Got a theory on why it's doing that. The compiler is seeing that the node contains options, so it adds a "run the options!" bytecode. But not all code paths actually ADD options, so it goes "run options! there are zero of them!" instead. 

If this is what's happening, fiz will be to make "run options!" just stop the execution if there are no options to show.

**Comment by desplesda** [comment]
I'm pretty sure that 82e00ffa16 fixes this; however, I checked it using this script, which includes syntax that's similar to the code in the image that @InfiniteAmmoInc posted, but isn't identical:

```
<<if false>>
	[[SHHH|NotDone]]
	[[Ugh fine sure|Done]]
<<endif>>
```

I'm pretty sure that I've fixed the same bug as described at the top of this thread, but to be super sure, @InfiniteAmmoInc, if you can send me the text of the file that you screenshotted, I can verify that the issue is now gone.
