### ISSUE TITLE
Colons seem to throw the parser off

### ISSUE THREAD

**Issue by InfiniteAmmoInc** [thesecretlab/YarnSpinner#28]
```
<<if $germ_home_quest is 0>>
    [[HomeQuestIntro]]
<<elseif $germ_home_quest is 1>>
    [[HomeQuestTrampoline]]
<<endif>>

<<if $germ_home_quest > 0>>
    <<hide Collision:GermOnPorch>>
<<endif>>
```

The parser fails on the last line. I'm seeing the same thing happening in other files that where ":" is used in a command line etc.

**Comment by desplesda** [comment]
Looks like it's not just colons - this fails to parse too:

`<<!@#$%^&*()⁄€‹›ﬁﬂ‡°·‚‘-=_+>>`

Looking at what the parser is doing, it's successfully reading the `<<` token, then `hide` but then reads `Collision:GermOnPorch>>`. It then doesn't find the `>>`, because that just got read, and ends up confused.

**Comment by desplesda** [comment]
Ok, I've fixed it for the specific case of colons, but not for the general case of arbitrary punctuation. That'll have to wait until later.

Source package is attached.

[YarnSpinner-0.9.7.2-1-gbb71920-development-source-minimal.unitypackage.zip](https://github.com/thesecretlab/YarnSpinner/files/150161/YarnSpinner-0.9.7.2-1-gbb71920-development-source-minimal.unitypackage.zip)
