### ISSUE TITLE
Way to list all variables in the Yarn Spinner Editor Window

### ISSUE THREAD

**Issue by InfiniteAmmoInc** [thesecretlab/YarnSpinner#32]
This might be handy for checking for variable name typos, if the editor window could list all variables used and how many times they were used. (looking at the ones used only 1 time would indicate maybe they were typos)

**Comment by desplesda** [comment]
Agreed. This becomes more useful when you check all Yarn scripts in the project at once, which the Editor window can do.

**Comment by desplesda** [comment]
This isn't _exactly_ what this issue was requesting, but 284ecae adds a feature to the editor window that lists any variable that is never read from, or never written to, across all nodes (see https://twitter.com/desplesda/status/716924386821804032) 

If you're looking to spot typos, this is what you want. As a result, I'm closing this issue. :+1: 

<img width="330" alt="screen shot 2016-04-04 at 8 00 51 pm" src="https://cloud.githubusercontent.com/assets/901768/14244723/f257dbe4-fa9f-11e5-8644-60e736370e9c.png">

**Comment by InfiniteAmmoInc** [comment]
Very cool!! :laughing:
