### ISSUE TITLE
Dialogue.visitedNodes should be settable

### ISSUE THREAD

**Issue by desplesda** [thesecretlab/YarnSpinner#46]
The `Dialogue` object maintains a list of visited nodes in the `visitedNodes` property. However, this list is reset whenever the `Dialogue` object starts; this is undesired behavior when then the game is saved and quit, then re-started.

To fix this, `Dialogue` should allow for setting the `visitedNodes` property.

**Comment by oscar91** [comment]
Hello :)

Since I did not find this on the master branch I compiled my own .dll adding the set on Dialogue.visitedNodes.
And I've noticed that this:
`Set {
VisitedNodeNames = new HashSet <String> (visitedNodes);
} `
Did not work for me, the value of visitedNodes did not change after setting it to a new value. Don't know why.

After changing it to:
`Set {
VisitedNodeNames = new HashSet <String> (value);
} `
Worked fine for me.

Just wanted to say it's a bug or anybody has the same problem.
