### ISSUE TITLE
Label-less options are immediately jumped to

### ISSUE THREAD

**Issue by tmunro** [thesecretlab/YarnSpinner#49]
Hi folks! I've been trying to understand why my options are sometimes ignored, and I think I've tracked it down to a couple of issues. First, it seems like options without labels are never presented. This can be tested by replacing the Start node in the simple example script with the following:

```
   A: Hey, I'm a character in a script!
   B: And I am too! You are talking to me!
   [[Leave]]
   [[LearnMore]]
```

This skips the option presentation and immediately goes to `Leave`. Even if one of them has a label, the label-less option will be called.

Second, spaces and punctuation don't appear to be valid in node names / labels, but this isn't really described anywhere. If that's intended, it would be great to update the documentation and potentially throw some more helpful errors.

The Yarn editor doesn't seem to have a problem showing node links in these cases, so I assume they're intended as options - otherwise I suppose that should be updated as well.

Thanks!

**Comment by desplesda** [comment]
Hi!

This behaviour is by design. Options that don't have a label cause Yarn Spinner to immediately jump to the designated node. If you want options to appear for the player to choose, put the label and a vertical bar in front of the node name.

````
[[Leave|Leave]]
[[Learn More|LearnMore]]
````

And yes, spaces and punctuation (apart from underscores and periods) aren't allowed in node names. The documentation should be updated - thanks for pointing that out!

**Comment by tmunro** [comment]
Ah, okay! That is definitely good to know. The [documentation](https://github.com/thesecretlab/YarnSpinner/blob/master/Documentation/Usage.md#options) very clearly says "You don't have to provide the label. Instead, you can just provide the node name..." so I suppose that should be updated as well.

Thanks for the quick reply!

**Comment by desplesda** [comment]
Done! Thanks for finding the opportunity for improvement 😄
