### ISSUE TITLE
Problem parsing if statements containing shortcut options

### ISSUE THREAD

**Issue by falcon1988** [thesecretlab/YarnSpinner#53]
When using if statements to determine whether dialogue options should be presented, the normal options method works as expected, displaying all options that meet their conditions, but the same implemented with shortcut options displays only the first shortcut option to meet it's condition.

e.g.
```
<<if $foundClues == true>>
[[Place discovered clues on the board|MurderBoard.AddClues]]
<<endif>>
<<if $foundSuspects == true>>
[[Place known suspects on the board|MurderBoard.AddSuspects]]
<<endif>>
<<if $foundClues == true and $foundSuspects == true>>
[[I should try to tie some of these clues to a suspect|MurderBoard.AddCluesToSuspects]]
<<endif>>
[[Leave the board|MurderBoard.Exit]]
```
This displays all options which have met their conditions.

```
<<if $foundClues == true>>
->Place discovered clues on the board
    [[MurderBoard.AddClues]]
<<endif>>
<<if $foundSuspects == true>>
->Place known suspects on the board
    [[MurderBoard.AddSuspects]]
<<endif>>
<<if $foundClues == true and $foundSuspects == true>>
->I should try to tie some of these clues to a suspect
    [[MurderBoard.AddCluesToSuspects]]
<<endif>>
->Leave the board
    [[MurderBoard.Exit]]
```
This displays only the first option which meets it's condition.

**Comment by desplesda** [comment]
If you want to conditionally show shortcut options, use this syntax:

```
->Place discovered clues on the board <<if $foundClues == true>>
    [[MurderBoard.AddClues]]
->Place known suspects on the board <<if $foundSuspects == true>>
    [[MurderBoard.AddSuspects]]
->I should try to tie some of these clues to a suspect <<if $foundClues == true and $foundSuspects == true>>
    [[MurderBoard.AddCluesToSuspects]]
->Leave the board
    [[MurderBoard.Exit]]
```

(This is actually [in the documentation](https://github.com/thesecretlab/YarnSpinner/blob/master/Documentation/Usage.md#shortcut-options), but the docs really do need some love.)

To fully explain why you're getting this behaviour: each of those three shortcut options is being parsed as an independent group that contains a single option, because the parser doesn't see any further `->` options after the first one. In your second example, the program goes through each of the if statements, encountering shortcut option groups, and presenting them.

This is different to the `[[` options, which work on the model of presenting all of the options that have been encountered when the program reaches the end of the current node, along the same style as Twine. So, in your first example, the program goes through each of the if statements, collecting options, finally adding the 'Leave the board' option. It then hits the end of the node, and presents all of the options it found.
