### ISSUE TITLE
NullReferenceException on NodeExist method

### ISSUE THREAD

**Issue by oscar91** [thesecretlab/YarnSpinner#75]
Hi! I'm having a problem with NodeExist.

I'm making a script that basically adds a text asset and then execute some other code.
I would like to check if the TextAsset that I'm going to add with AddScript has not been added yet, so first, I call:
```
if(!FindObjectOfType<Yarn.Unity.DialogueRunner>().NodeExists(talkToNode))
{
//If the node doesn't exist, add the conversation
FindObjectOfType<Yarn.Unity.DialogueRunner>().AddScript(yarnConversation);
}
```

But it throws this:

> NullReferenceException: Object reference not set to an instance of an object
> Yarn.Dialogue.NodeExists (System.String nodeName)
> Yarn.Unity.DialogueRunner.NodeExists (System.String nodeName) (at Assets/Scripts/Yarn Spinner/Code/DialogueRunner.cs:223)

I noticed that if I call AddScript() before calling NodeExist(), it works fine, without throwing NullReferenceException. But I obviously need to check if node exist before add it. 

I know its an easy error, but I can't figure out what is null. I debugged, and everything is fine until it executes
```
public bool NodeExists(string nodeName) {
			return dialogue.NodeExists(nodeName);
		}
```
on DialogueRunner Class. So the thing must be on Dialogue class, wich I can't debug (because of the dll)

I don't know if I'm doing a wrong use of NodeExist or what.

Thanks so much for reading
Cheers :)

**Comment by oscar91** [comment]
I think I was using it wrong. If I'm not mistaken, throws NullReferenceException because dialogue refers to an active conversation (?), and at the moment it execute NodeExist there is any active dialogue, so it's null.

If it's so, there is any way to check if a certain yarn text has already been added?

**Comment by bowlercaptain** [comment]
It sure *seems* like DR.dialogue [should never be null](https://github.com/thesecretlab/YarnSpinner/blob/master/Unity/Assets/YarnSpinner/Code/DialogueRunner.cs#L79). So the only way to get an NRE would be because of the dialogue's "program" being null, which has no such guarantees. 

Probably could check if program or nodes are null, and return false if so.

**Comment by TheMartianLife** [comment]
Hi!

Might be a bit late, but the issue is as @bowlercaptain says. It sounds like you're trying to call `dialogue.NodeExists()`the first time before `dialogue` exists yet. So it's not amazing, but the solution is probably something like 

```csharp
public bool NodeExists(string nodeName) {
    if (dialogue == null) { 
        return false; // skip check if no object to check
    }

    return dialogue.NodeExists(nodeName);
}
``` 

We'll have a look at adding something like this on our end to support this in the future. Good luck!
